controller_manager:
  ros__parameters:
    update_rate: 125  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_state_controller:
      type: joint_state_controller/JointStateController

    forward_position_controller:              # delete entry if controller is not applicable
      type: forward_command_controller/ForwardCommandController

    forward_velocity_controller:              # delete entry if controller is not applicable
      type: forward_command_controller/ForwardCommandController

    joint_trajectory_controller:              # delete entry if controller is not applicable
      type: joint_trajectory_controller/JointTrajectoryController

forward_position_controller:                  # delete entry if controller is not applicable
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: position

forward_velocity_controller:                  # delete entry if controller is not applicable
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: velocity

joint_trajectory_controller:                  # delete entry if controller is not applicable
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    state_publish_rate: 100.0
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false # Defaults to false
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)